language: node_js
node_js:
  - 8
before_script:
  - npm install @11ty/eleventy -g
script: eleventy
deploy:
  local-dir: _site
  provider: pages
  target_branch: master # Github pages accepts only master for <username>.github.io urls
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: source
